name: Push build

on:
  push:
    branches:
      - master
      - honister
      - dunfell

jobs:
  build:
    uses: ./.github/workflows/build-template.yml
    with:
      host: ubuntu-20.04
      images: core-image-base core-image-weston core-image-x11 initramfs-test-image initramfs-test-full-image initramfs-firmware-image initramfs-rootfs-image cryptodev-module
      machines: qcom-armv8a sdx55-mtp qcom-armv7a
      ref: ${{github.sha}}
      ref_type: sha
      branch: ${{github.ref_name}}
      url: ${{github.server_url}}/${{github.repository}}
    secrets: inherit
