name: Push build

on:
  push:
    branches:
      - master
      - honister
      - dunfell

jobs:
  build:
    uses: ndechesne/meta-qcom/.github/workflows/build-template.yml@master
    with:
      host: ubuntu-20.04
      images: core-image-base core-image-weston core-image-x11 initramfs-test-image initramfs-test-full-image initramfs-firmware-image initramfs-rootfs-image cryptodev-module
      machines: >-
        ['dragonboard-410c', 'dragonboard-845c', 'qrb5165-rb5', 'qcom-armv8a', 'sdx55-mtp', 'sa8155p-adp', 'qcom-armv7a']
      ref: ${{github.sha}}
      branch: ${{github.ref_name}}
      url: ${{github.server_url}}/${{github.repository}}
    secrets: inherit
